using Microsoft.CodeAnalysis; using Microsoft.CodeAnalysis.CSharp; using Microsoft.CodeAnalysis.CSharp.Syntax;
namespace QualityReporter.CSharp.SymbolExtraction;
public sealed class CSharpSymbolExtractor(MethodAnalysisConfig? options=null):ISymbolExtractor
{
    private readonly MethodAnalysisConfig options=options??new();
    public IReadOnlyList<SymbolResult> Extract(string path,string source){var tree=CSharpSyntaxTree.ParseText(source,path:path);var compilation=CSharpCompilation.Create("SymbolExtraction",[tree],[MetadataReference.CreateFromFile(typeof(object).Assembly.Location)]);var semantic=compilation.GetSemanticModel(tree,true);return tree.GetRoot().DescendantNodes().Where(Eligible).Select(n=>Create(tree,semantic,n)).Where(x=>x is not null).Cast<SymbolResult>().ToList();}
    private bool Eligible(SyntaxNode n)=>n switch{ConstructorDeclarationSyntax=>options.IncludeConstructors,LocalFunctionStatementSyntax=>options.IncludeLocalFunctions,AccessorDeclarationSyntax=>options.IncludeAccessors,MethodDeclarationSyntax or OperatorDeclarationSyntax or ConversionOperatorDeclarationSyntax=>true,_=>false};
    private SymbolResult? Create(SyntaxTree tree,SemanticModel semantic,SyntaxNode node){var symbol=semantic.GetDeclaredSymbol(node) as IMethodSymbol;if(symbol is null||symbol.IsImplicitlyDeclared)return null;var key=CSharpSymbolIdentityBuilder.BuildKey(symbol);var span=tree.GetLineSpan(node.Span);var kind=node switch{ConstructorDeclarationSyntax=>"constructor",LocalFunctionStatementSyntax=>"local-function",AccessorDeclarationSyntax a=>a.IsKind(SyntaxKind.GetAccessorDeclaration)?"getter":"setter",OperatorDeclarationSyntax or ConversionOperatorDeclarationSyntax=>"operator",_=>"method"};var name=node is AccessorDeclarationSyntax?symbol.AssociatedSymbol?.Name+"."+symbol.Name:symbol.Name;return new(){SymbolId=CSharpSymbolIdentityBuilder.BuildId(key),SymbolKey=key,Name=name,Kind=kind,Location=new(span.StartLinePosition.Line+1,span.EndLinePosition.Line+1),Metrics=new(){Loc=span.EndLinePosition.Line-span.StartLinePosition.Line+1,Complexity=CSharpComplexityCalculator.Calculate(node,options.CountLogicalOperators)}};}
}
