using Xunit;using QualityReporter.CSharp;using QualityReporter.CSharp.Analysis;using QualityReporter.CSharp.Git;
public class CoreTests {
 static FileResult F(string p,int n)=>new(){Path=p,Metrics=new(){Complexity=n},History=new(){CommitCount=n,Churn=n,AuthorCount=n,ReworkRate=n/10d,FileAgeDays=60},Couplings=[]};
 [Fact] public void Activity_and_risk_are_separate_and_missing_coverage_is_normalized(){var fs=new List<FileResult>{F("a",1),F("b",9)};RiskCalculator.Calculate(fs,new());ActivityCalculator.Calculate(fs,new(),new());Assert.Equal(0,fs[0].Risk.Score);Assert.True(fs[1].Risk.Score > 0);Assert.Equal(90,fs[1].Activity.Score);Assert.Null(fs[1].Risk.CoverageRiskPercentile);}
 [Theory][InlineData(3,.65)][InlineData(20,.8)][InlineData(60,1)] public void Maturity_uses_file_age(int age,double factor){var f=F("x",1);f.History.FileAgeDays=age;ActivityCalculator.Calculate([f],new(),new());Assert.Equal(factor,f.Activity.MaturityFactor);}
 [Fact] public void Critical_risk_bypasses_maturity(){var f=F("x",1);f.Activity.Score=100;f.Activity.EffectiveScore=65;f.Risk.Score=80;HotspotPriorityCalculator.Calculate([f],new());Assert.Equal(100,f.Activity.EffectiveScore);}
 [Fact] public void Classifier_and_recommendations_are_rule_based(){var f=F("x",9);f.Metrics.LineCoverage=40;f.Risk.ComplexityPercentile=.9;f.Risk.ReworkPercentile=.9;f.Risk.Score=90;f.Activity.Score=f.Activity.EffectiveScore=90;f.Hotspot.PriorityScore=90;HotspotClassifier.Classify([f],new());RecommendationEngine.Generate([f]);Assert.Contains("critical",f.Hotspot.Classifications);Assert.Contains(f.Recommendations,x=>x.Code=="ADD_TEST_BEFORE_REFACTOR"&&x.Evidence.Count>0);}
 [Fact] public void Git_aggregates_dates(){var at=DateTimeOffset.UtcNow.AddDays(-2);var(h,_)=GitHistoryAnalyzer.Aggregate([new("1",at,"a",false,new(){{"a.cs",(1,1)}})],new());Assert.Equal(at,h["a.cs"].FirstCommitAt);Assert.NotNull(h["a.cs"].FileAgeDays);}
}

public class QualityAxesV14Tests {
 [Fact] public void Missing_metrics_are_renormalized(){var c=new QualityReporter.CSharp.Analysis.Axes.TestabilityRiskCalculator(new());var s=c.Calculate(new Dictionary<string,double?>{{"untestedComplexity",100},{"lineCoverage",null},{"branchCoverage",null}});Assert.Equal(100,s.Score);Assert.Equal(55,s.AvailableWeight);}
 [Fact] public void Missing_axis_is_unknown(){var c=new QualityReporter.CSharp.Analysis.Axes.ArchitectureRiskCalculator(new());var s=c.Calculate(new Dictionary<string,double?>{{"changeCoupling",null},{"issues",null}});Assert.Null(s.Score);Assert.Equal("unknown",s.Level);}
 [Fact] public void Quality_axes_preserve_legacy_risk_and_emit_only_supported_scores(){var f=File();RiskCalculator.Calculate([f],new());f.Hotspot.PriorityScore=37;var legacy=(f.Risk.Score,f.Risk.Level,f.Risk.MaintainabilityScore,f.Risk.TestScore,f.Risk.ArchitectureScore);QualityScoresCalculator.Calculate([f],new());Assert.Equal(legacy,(f.Risk.Score,f.Risk.Level,f.Risk.MaintainabilityScore,f.Risk.TestScore,f.Risk.ArchitectureScore));Assert.Equal(37,f.Hotspot.PriorityScore);Assert.NotNull(f.Scores.OverallQuality);Assert.Null(typeof(QualityScores).GetProperty("Knowledge"));}
 [Fact] public void Unavailable_analyzer_issues_are_omitted_from_quality_axes(){var files=new List<FileResult>{File(1),File(9)};RiskCalculator.Calculate(files,new(),false);QualityScoresCalculator.Calculate(files,new());foreach(var f in files){Assert.Null(f.Risk.IssuePercentile);Assert.DoesNotContain("issues",f.Scores.Maintainability.Components.Keys);Assert.DoesNotContain("issues",f.Scores.Architecture.Components.Keys);}}
 static FileResult File(int complexity=1)=>new(){Path="a.cs",Metrics=new(){Loc=10,Complexity=complexity},History=new(){CommitCount=1,Churn=1,AuthorCount=1},Activity=new(){Score=50,EffectiveScore=50}};
}
