namespace QualityReporter.CSharp;
public sealed class Config { public UntestedComplexityConfig UntestedComplexity {get;set;}=new(); public DuplicationConfig Duplication {get;set;}=new(); public int HistoryDays {get;set;}=180; public int ReworkWindowDays {get;set;}=30; public string[] Exclude {get;set;}=["**/bin/**","**/obj/**","**/node_modules/**","**/dist/**","**/build/**","**/coverage/**","**/generated/**","**/*.generated.cs","**/*.g.cs","**/*.designer.cs"]; public CouplingConfig Coupling {get;set;}=new(); public FileMaturityConfig FileMaturity {get;set;}=new(); public ActivityWeights ActivityWeights {get;set;}=new(); public RiskWeights RiskWeights {get;set;}=new(); public ClassificationConfig Classification {get;set;}=new(); public FunctionConfig Functions {get;set;}=new(); public MethodAnalysisConfig MethodAnalysis {get;set;}=new(); public ReportConfig Report {get;set;}=new(); }
public sealed class UntestedComplexityConfig { public bool Enabled {get;set;}=true; public string CoverageMode {get;set;}="line"; public int ComplexityWarning {get;set;}=15; public int ComplexityCritical {get;set;}=25; public double LowCoverage {get;set;}=.60; public double CriticalCoverage {get;set;}=.50; }
public sealed class DuplicationConfig { public bool Enabled {get;set;}=true; public string ReportPath {get;set;}="reports/jscpd.json"; public double WarningPercentage {get;set;}=.20; public double StrongPercentage {get;set;}=.40; public int MinimumLines {get;set;}=5; public int MinimumTokens {get;set;}=50; }
public sealed class CouplingConfig { public int MaxFilesPerCommit {get;set;}=20; public int MinCount {get;set;}=3; public double MinRatio {get;set;}=.3; }
public sealed class FileMaturityConfig { public bool Enabled {get;set;}=true; public double FirstWeekFactor {get;set;}=.65; public double FirstMonthFactor {get;set;}=.8; public double CriticalRiskBypass {get;set;}=80; }
public sealed class ActivityWeights { public double Change {get;set;}=45; public double Churn {get;set;}=35; public double Authors {get;set;}=10; public double Recency {get;set;}=10; }
public sealed class RiskWeights { public double Complexity {get;set;}=25; public double Rework {get;set;}=25; public double Duplication {get;set;}=20; public double Coupling {get;set;}=15; public double Issues {get;set;}=15; public double CoverageRisk {get;set;}=40; public double UntestedComplexity {get;set;}=60; }
public sealed class ClassificationConfig { public double HighActivity {get;set;}=70; public double HighComplexityPercentile {get;set;}=.8; public double HighReworkPercentile {get;set;}=.8; public double LowCoverage {get;set;}=60; public double CriticalPriority {get;set;}=80; }
public sealed class FunctionConfig { public int ComplexityWarning {get;set;}=15; public int ComplexityCritical {get;set;}=25; }
public sealed class MethodAnalysisConfig { public bool Enabled {get;set;}=true; public bool HistoryEnabled {get;set;}=true; public bool IncludeConstructors {get;set;}=true; public bool IncludeAccessors {get;set;} public bool IncludeLocalFunctions {get;set;}=true; public bool IncludeAnonymousFunctions {get;set;} public bool CountLogicalOperators {get;set;}=true; public int ComplexityWarning {get;set;}=15; public int ComplexityCritical {get;set;}=25; public MethodCouplingConfig Coupling {get;set;}=new(); public RenameTrackingConfig RenameTracking {get;set;}=new(); }
public sealed class MethodCouplingConfig { public bool Enabled {get;set;}=true; public bool CrossFile {get;set;} public int MaxSymbolsPerCommit {get;set;}=20; public int MinCount {get;set;}=3; public double MinRatio {get;set;}=.3; }
public sealed class RenameTrackingConfig { public bool Enabled {get;set;} public double SimilarityThreshold {get;set;}=.8; }
public sealed class ReportConfig { public int TopHotspots {get;set;}=20; public int DetailedRecommendations {get;set;}=10; }
public sealed record CommitChange(string Hash, DateTimeOffset At, string Email, bool Merge, Dictionary<string,(int Add,int Delete)> Files);
public sealed class HistoryMetrics { public int CommitCount {get;set;} public int Churn {get;set;} public int AuthorCount {get;set;} public double ReworkRate {get;set;} public DateTimeOffset? FirstCommitAt {get;set;} public DateTimeOffset? LastChangedAt {get;set;} public int? FileAgeDays {get;set;} }
public sealed record Coupling(string File,string CoupledWith,int Count,double Ratio);
public sealed record FunctionMetric(string Name,string Kind,int StartLine,int EndLine,int Complexity);
public sealed record SymbolLocation(int StartLine,int EndLine);
public sealed class UntestedComplexityMetric { public double Raw {get;set;} public double? Percentile {get;set;} }
public sealed class DuplicationMetric { public int DuplicatedLines {get;set;} public double DuplicatedPercentage {get;set;} public int DuplicateGroupCount {get;set;} public double? RiskPercentile {get;set;} }
public sealed class SymbolMetric { public int Loc {get;set;} public int Complexity {get;set;} public double? LineCoverage {get;set;} public double? BranchCoverage {get;set;} public int Issues {get;set;} public UntestedComplexityMetric? UntestedComplexity {get;set;} public DuplicationMetric? Duplication {get;set;} }
public sealed class SymbolResult { public required string SymbolId {get;set;} public required string SymbolKey {get;set;} public required string Name {get;set;} public required string Kind {get;set;} public required SymbolLocation Location {get;set;} public SymbolMetric Metrics {get;set;}=new(); public HistoryMetrics History {get;set;}=new(); public Activity Activity {get;set;}=new(); public Risk Risk {get;set;}=new(); public Hotspot Hotspot {get;set;}=new(); public List<Coupling> Couplings {get;set;}=[]; public List<Recommendation> Recommendations {get;set;}=[]; public List<string> DuplicateGroups {get;set;}=[]; }
public sealed record MethodSummary(int SymbolCount,int CriticalCount,int HighCount,double MaxPriority,double MaxRisk,int HighComplexityCount,int HighReworkCount);
public sealed class CodeMetric { public int Loc {get;set;} public int Complexity {get;set;} public double? MaintainabilityIndex {get;set;} public double? LineCoverage {get;set;} public double? BranchCoverage {get;set;} public IssueCounts Issues {get;set;}=new(); public UntestedComplexityMetric? UntestedComplexity {get;set;} public DuplicationMetric? Duplication {get;set;} }
public sealed class IssueCounts { public int Error {get;set;} public int Warning {get;set;} public int Info {get;set;} }
public sealed class Activity { public double? ChangePercentile {get;set;} public double? ChurnPercentile {get;set;} public double? AuthorPercentile {get;set;} public double? RecencyPercentile {get;set;} public double Score {get;set;} public double MaturityFactor {get;set;}=1; public double EffectiveScore {get;set;} }
public sealed class Risk { public double? ComplexityPercentile {get;set;} public double? ReworkPercentile {get;set;} public double? CoverageRiskPercentile {get;set;} public double? CouplingRiskPercentile {get;set;} public double? IssuePercentile {get;set;} public double? DuplicationRiskPercentile {get;set;} public double MaintainabilityScore {get;set;} public double? TestScore {get;set;} public double ArchitectureScore {get;set;} public double Score {get;set;} public string Level {get;set;}="low"; }
public sealed class Hotspot { public double PriorityScore {get;set;} public string? PrimaryClassification {get;set;} public List<string> Classifications {get;set;}=[]; }
public sealed record Recommendation(string Code,int Priority,string Message,List<string> Evidence);
public sealed class FileResult { public required string Path {get;set;} public CodeMetric Metrics {get;set;}=new(); public HistoryMetrics History {get;set;}=new(); public Activity Activity {get;set;}=new(); public Risk Risk {get;set;}=new(); public Hotspot Hotspot {get;set;}=new(); public List<Recommendation> Recommendations {get;set;}=[]; public List<Coupling> Couplings {get;set;}=[]; public List<FunctionMetric> Functions {get;set;}=[]; public List<SymbolResult> Symbols {get;set;}=[]; public List<string> DuplicateGroups {get;set;}=[]; public MethodSummary? MethodSummary {get;set;} }
public sealed class Report { public int SchemaVersion {get;set;}=1; public string Language {get;set;}="csharp"; public DateTimeOffset GeneratedAt {get;set;}=DateTimeOffset.UtcNow; public object Repository {get;set;}=new{}; public object Summary {get;set;}=new{}; public List<string> Warnings {get;set;}=[]; public object? Trend {get;set;} public List<FileResult> Files {get;set;}=[]; public List<DuplicateGroup> Duplicates {get;set;}=[]; }
