namespace QualityReporter.CSharp;
public sealed class Config { public int HistoryDays {get;set;}=180; public int ReworkWindowDays {get;set;}=30; public string[] Exclude {get;set;}=["**/bin/**","**/obj/**","**/node_modules/**","**/dist/**","**/build/**","**/coverage/**","**/generated/**","**/*.generated.cs","**/*.g.cs","**/*.designer.cs"]; public CouplingConfig Coupling {get;set;}=new(); public RiskWeights RiskWeights {get;set;}=new(); }
public sealed class CouplingConfig { public int MaxFilesPerCommit {get;set;}=20; public int MinCount {get;set;}=3; public double MinRatio {get;set;}=.3; }
public sealed class RiskWeights { public double Change {get;set;}=25; public double Churn {get;set;}=15; public double Rework {get;set;}=20; public double Complexity {get;set;}=20; public double Coverage {get;set;}=15; public double Issues {get;set;}=5; }
public sealed record CommitChange(string Hash, DateTimeOffset At, string Email, bool Merge, Dictionary<string,(int Add,int Delete)> Files);
public sealed class HistoryMetrics { public int CommitCount {get;set;} public int Churn {get;set;} public int AuthorCount {get;set;} public double ReworkRate {get;set;} public DateTimeOffset? LastChangedAt {get;set;} }
public sealed record Coupling(string File,string CoupledWith,int Count,double Ratio);
public sealed record FunctionMetric(string Name,string Kind,int StartLine,int EndLine,int Complexity);
public sealed class CodeMetric { public int Loc {get;set;} public int Complexity {get;set;} public double? MaintainabilityIndex {get;set;} public double? LineCoverage {get;set;} public double? BranchCoverage {get;set;} public IssueCounts Issues {get;set;}=new(); }
public sealed class IssueCounts { public int Error {get;set;} public int Warning {get;set;} public int Info {get;set;} }
public sealed class Risk { public double? ChangePercentile {get;set;} public double? ChurnPercentile {get;set;} public double? ReworkPercentile {get;set;} public double? ComplexityPercentile {get;set;} public double? CoverageRiskPercentile {get;set;} public double? IssuePercentile {get;set;} public double Score {get;set;} public string Level {get;set;}="low"; }
public sealed class FileResult { public required string Path {get;set;} public CodeMetric Metrics {get;set;}=new(); public HistoryMetrics History {get;set;}=new(); public Risk Risk {get;set;}=new(); public List<Coupling> Couplings {get;set;}=[]; public List<FunctionMetric> Functions {get;set;}=[]; }
public sealed class Report { public int SchemaVersion {get;set;}=1; public string Language {get;set;}="csharp"; public DateTimeOffset GeneratedAt {get;set;}=DateTimeOffset.UtcNow; public object Repository {get;set;}=new{}; public object Summary {get;set;}=new{}; public List<string> Warnings {get;set;}=[]; public object? Trend {get;set;} public List<FileResult> Files {get;set;}=[]; }
