using System.Diagnostics; using System.Text;
namespace QualityReporter.CSharp.Git;
public interface IGitCommandRunner { string Run(string workingDirectory, params string[] args); }
public sealed class GitCommandRunner : IGitCommandRunner { public string Run(string wd,params string[] args) { var p=new Process{StartInfo=new("git"){WorkingDirectory=wd,RedirectStandardOutput=true,RedirectStandardError=true,UseShellExecute=false}}; foreach(var a in args)p.StartInfo.ArgumentList.Add(a); p.Start(); var o=p.StandardOutput.ReadToEnd(); var e=p.StandardError.ReadToEnd(); p.WaitForExit(); if(p.ExitCode!=0)throw new InvalidOperationException(e.Trim()); return o; } }
public sealed class GitHistoryAnalyzer(IGitCommandRunner git) {
 public (Dictionary<string,HistoryMetrics>,List<Coupling>) Analyze(string root,int days,Config cfg) { var raw=git.Run(root,"log",$"--since={days} days ago","--no-merges","--numstat","--date=iso-strict","--format=@@%H%x09%aI%x09%ae"); return Aggregate(Parse(raw),cfg); }
 public static List<CommitChange> Parse(string raw) { var result=new List<CommitChange>(); string? hash=null,email=null; DateTimeOffset at=default; Dictionary<string,(int,int)> files=[]; void Flush(){if(hash!=null)result.Add(new(hash,at,email!,false,files));} foreach(var line in raw.Split('\n')) { if(line.StartsWith("@@")){Flush(); var p=line[2..].Split('\t'); hash=p[0];at=DateTimeOffset.Parse(p[1]);email=p[2];files=[];} else {var p=line.Split('\t');if(p.Length>=3&&int.TryParse(p[0],out var a)&&int.TryParse(p[1],out var d))files[Normalize(p[2])]=(a,d);}} Flush(); return result; }
 static string Normalize(string p) { if(p.Contains(" => ")) { var open=p.IndexOf('{');var close=p.IndexOf('}'); if(open>=0&&close>open){var inside=p[(open+1)..close];p=p[..open]+inside.Split(" => ")[^1]+p[(close+1)..];} else p=p.Split(" => ")[^1];} return p.Replace('\\','/'); }
 public static (Dictionary<string,HistoryMetrics>,List<Coupling>) Aggregate(IEnumerable<CommitChange> input,Config cfg) { var commits=input.Where(c=>!c.Merge).ToList(); var map=new Dictionary<string,HistoryMetrics>(); foreach(var g in commits.SelectMany(c=>c.Files.Select(f=>(c,f))).GroupBy(x=>x.f.Key)){var ordered=g.OrderBy(x=>x.c.At).ToList();var rework=ordered.Zip(ordered.Skip(1)).Count(x=>(x.Second.c.At-x.First.c.At).TotalDays<=cfg.ReworkWindowDays);map[g.Key]=new(){CommitCount=ordered.Count,Churn=ordered.Sum(x=>x.f.Value.Add+x.f.Value.Delete),AuthorCount=ordered.Select(x=>x.c.Email).Distinct(StringComparer.OrdinalIgnoreCase).Count(),PrimaryAuthorRatio=ordered.Count==0?null:ordered.GroupBy(x=>x.c.Email,StringComparer.OrdinalIgnoreCase).Max(a=>(double)a.Sum(x=>x.f.Value.Add+x.f.Value.Delete))/Math.Max(1,ordered.Sum(x=>x.f.Value.Add+x.f.Value.Delete)),ReworkRate=ordered.Count==0?0:(double)rework/ordered.Count,FirstCommitAt=ordered.Min(x=>x.c.At),LastChangedAt=ordered.Max(x=>x.c.At),FileAgeDays=Math.Max(0,(int)(DateTimeOffset.UtcNow-ordered.Min(x=>x.c.At)).TotalDays)};} var pairs=new Dictionary<(string,string),int>();foreach(var c in commits.Where(c=>c.Files.Count<=cfg.Coupling.MaxFilesPerCommit)){var fs=c.Files.Keys.Order().ToArray();for(int i=0;i<fs.Length;i++)for(int j=i+1;j<fs.Length;j++)pairs[(fs[i],fs[j])]=pairs.GetValueOrDefault((fs[i],fs[j]))+1;}var couplings=new List<Coupling>();foreach(var (p,n) in pairs){foreach(var (a,b) in new[]{p,(p.Item2,p.Item1)}){var ratio=(double)n/map[a].CommitCount;if(n>=cfg.Coupling.MinCount&&ratio>=cfg.Coupling.MinRatio)couplings.Add(new(a,b,n,ratio));}}return(map,couplings); }
}
