namespace QualityReporter.CSharp.Analysis;
internal static class Percentiles
{
 internal static void Set<T>(List<FileResult> fs,Func<FileResult,T> value,Action<FileResult,double> set) where T:IComparable<T>{if(fs.Count==0)return;var sorted=fs.Select(value).Order().ToList();var same=sorted.Count<2||sorted[0].CompareTo(sorted[^1])==0;foreach(var f in fs){var v=value(f);var below=sorted.Count(x=>x.CompareTo(v)<0);var equal=sorted.Count(x=>x.CompareTo(v)==0);set(f,same?0:(below+(equal-1)/2d)/(sorted.Count-1));}}
 internal static double Weighted(params (double? Value,double Weight)[] terms){var a=terms.Where(x=>x.Value.HasValue&&x.Weight>0).ToList();return a.Count==0?0:Math.Round(a.Sum(x=>x.Value!.Value*x.Weight)/a.Sum(x=>x.Weight)*100,1);}
}
public static class RiskCalculator
{
 public static void Calculate(List<FileResult> files,RiskWeights w){Percentiles.Set(files,x=>x.History.ReworkRate,(f,p)=>f.Risk.ReworkPercentile=p);Percentiles.Set(files,x=>x.Metrics.Complexity,(f,p)=>f.Risk.ComplexityPercentile=p);Percentiles.Set(files,x=>x.Couplings.Select(c=>c.Ratio).DefaultIfEmpty().Max(),(f,p)=>f.Risk.CouplingRiskPercentile=p);Percentiles.Set(files,x=>x.Metrics.Issues.Error+x.Metrics.Issues.Warning+x.Metrics.Issues.Info,(f,p)=>f.Risk.IssuePercentile=p);var covered=files.Where(x=>x.Metrics.LineCoverage.HasValue).ToList();Percentiles.Set(covered,x=>-x.Metrics.LineCoverage!.Value,(f,p)=>f.Risk.CoverageRiskPercentile=p);var uc=files.Where(x=>x.Metrics.UntestedComplexity is not null).ToList();Percentiles.Set(uc,x=>x.Metrics.UntestedComplexity!.Raw,(f,p)=>f.Metrics.UntestedComplexity!.Percentile=p);var duplicated=files.Where(x=>x.Metrics.Duplication is not null).ToList();Percentiles.Set(duplicated,x=>DuplicationRiskCalculator.Calculate(x.Metrics.Duplication!.DuplicatedPercentage,x.Activity.EffectiveScore),(f,p)=>{f.Metrics.Duplication!.RiskPercentile=p;f.Risk.DuplicationRiskPercentile=p;});foreach(var f in files){f.Risk.MaintainabilityScore=Percentiles.Weighted((f.Risk.ComplexityPercentile,w.Complexity),(f.Risk.ReworkPercentile,w.Rework),(f.Risk.DuplicationRiskPercentile,w.Duplication),(f.Risk.CouplingRiskPercentile,w.Coupling),(f.Risk.IssuePercentile,w.Issues));f.Risk.TestScore=f.Risk.CoverageRiskPercentile.HasValue?Percentiles.Weighted((f.Risk.CoverageRiskPercentile,w.CoverageRisk),(f.Metrics.UntestedComplexity?.Percentile,w.UntestedComplexity)):null;f.Risk.ArchitectureScore=Percentiles.Weighted((f.Risk.CouplingRiskPercentile,1));f.Risk.Score=Percentiles.Weighted((f.Risk.MaintainabilityScore/100,.5),(f.Risk.TestScore/100,.3),(f.Risk.ArchitectureScore/100,.2));f.Risk.Level=f.Risk.Score>=80?"critical":f.Risk.Score>=60?"high":f.Risk.Score>=40?"medium":"low";}}
}
public static class BaselineComparer { public static object Compare(Report current,Report old){var now=current.Files.ToDictionary(x=>x.Path);var before=old.Files.ToDictionary(x=>x.Path);return new{newCritical=now.Values.Where(x=>x.Risk.Level=="critical"&&(!before.TryGetValue(x.Path,out var b)||b.Risk.Level!="critical")).Select(x=>x.Path),resolvedCritical=before.Values.Where(x=>x.Risk.Level=="critical"&&(!now.TryGetValue(x.Path,out var n)||n.Risk.Level!="critical")).Select(x=>x.Path),newHotspots=now.Values.Where(x=>x.Hotspot.PriorityScore>=60&&(!before.TryGetValue(x.Path,out var b)||b.Hotspot.PriorityScore<60)).Select(x=>x.Path),resolvedHotspots=before.Values.Where(x=>x.Hotspot.PriorityScore>=60&&(!now.TryGetValue(x.Path,out var n)||n.Hotspot.PriorityScore<60)).Select(x=>x.Path),riskIncreased=now.Values.Where(x=>before.TryGetValue(x.Path,out var b)&&x.Risk.Score>b.Risk.Score).Select(x=>x.Path),riskDecreased=now.Values.Where(x=>before.TryGetValue(x.Path,out var b)&&x.Risk.Score<b.Risk.Score).Select(x=>x.Path),priorityIncreased=now.Values.Where(x=>before.TryGetValue(x.Path,out var b)&&x.Hotspot.PriorityScore>b.Hotspot.PriorityScore).Select(x=>x.Path),priorityDecreased=now.Values.Where(x=>before.TryGetValue(x.Path,out var b)&&x.Hotspot.PriorityScore<b.Hotspot.PriorityScore).Select(x=>x.Path),newUntestedComplexMethods=now.Values.Where(x=>x.Hotspot.Classifications.Contains("untested_complex")&&(!before.TryGetValue(x.Path,out var b)||!b.Hotspot.Classifications.Contains("untested_complex"))).Select(x=>x.Path),newDuplicateHotspots=now.Values.Where(x=>x.Hotspot.Classifications.Contains("duplicated")&&x.Hotspot.PriorityScore>=80&&(!before.TryGetValue(x.Path,out var b)||!b.Hotspot.Classifications.Contains("duplicated"))).Select(x=>x.Path)};}}
